wanasit/chrono

src/parsers/EN/ENISOFormatParser.js, src/result.js, test-qunit/test_en.js, test-qunit/test_en_time_exp.js
The millisecond component of an ISO formatted string is no longer discarded
=> ISO format milliseconds are preserved

README.md
The documentation was not updated after #22 was closed with added Bower
support. This commit fixes this.
Thanks!
=> Add information about installation via Bower

src/options.js, src/parsers/EN/ENDateFormatParser.js, src/parsers/EN/ENMonthNameLittleEndianParser.js, src/parsers/EN/ENMonthNameMiddleEndianParser.js, src/parsers/EN/ENSlashDateFormatParser.js, test-qunit/test_en.js, test-qunit/test_en_middle_endian.js
Also changed to recognize unambiguous dd-mm-yyyy.
Also simplified regexp for day of week.
=> Fixed https://github.com/wanasit/chrono/issues/58 dash was not allowed

src/parsers/EN/ENWeekdayParser.js
=> Use keys from DAYS_OFFSET in the regular expression, so adding keys can

README.md
=> Change Guild to Guide

src/parsers/EN/ENCasualDateParser.js, test/test_en_casual.js
The casual parsers for other languages than English support parsing "tomorrow morning" etc.
This PR adds this capability to the English parser.
=> Support for parsing 'tomorrow morning', 'yesterday evening' (English)

src/parsers/FR/FRMonthNameLittleEndianParser.js, test/test_fr_little_endian.js
Quite often the 1st day of month is written "1er" (following the language)
I added a test for the case, but sorry forgot to create a branch!
Cheers
=> added fr culture's first day of month parsing

src/parsers/EN/ENTimeExpressionParser.js
Fixes #152.
Also the new MacBook Pro w/ Touchbar comes with a great feature - AUTOCORRECT (🎉)! The commit message is messed up.
=> Make the preposition matcher in front of time lazy

README.md
This PR fixes minor inconsistencies in `README.md`, including:
- missing highlighting of code block elements
- javascript styling inconsistency in coding examples
=> Improve consistency in README.md

package.json, src/parsers/en/ENTimeLaterFormatParser.js, src/utils/EN.js, test/en/en_time_from_now.test.js, test/en/en_time_later.test.js
First of all, thanks for creating this project!
I use it in a [small web reminder utility](https://hryanjones.com/webminder/) that I've been working on.
I found that I was very commonly writing strings like "in 1.5 hours" and a bit frustrated that they didn't work, so I've added support for this. I'll try to add comments to the PR to explain some of the reasons for things that may not be clear.
Thanks again!
=> Add English support for relative phrases like "in 1.5 hours".

src/results.ts, test/result.test.ts
=> typing-fix: ParsingComponents.get: number | undefined -> number | null

src/locales/nl/constants.ts, src/locales/nl/index.ts, src/locales/nl/parsers/NLRelativeDateFormatParser.ts, src/locales/nl/parsers/NLTimeExpressionParser.ts, src/locales/nl/parsers/NLTimeUnitAgoFormatParser.ts, src/locales/nl/parsers/NLTimeUnitCasualRelativeFormatParser.ts, src/locales/nl/parsers/NLTimeUnitLaterFormatParser.ts, test/nl/nl_relative.test.ts, test/nl/nl_time_units_ago.test.ts, test/nl/nl_time_units_casual_relative.test.ts, test/nl/nl_time_units_later.test.ts
I've tried to add more support for the Dutch language (I'm not a native speaker so it's based on Google translate and some help from a client).
Since rebasing off master today all of the tests have broken - they seem to be broken in master so I don't think it's anything I've done.
=> Added more support for Dutch.

README.md
update to the results[0].index; example value
=> README.md .index example correction

test/en/en_relative.test.ts, test/en/en_time_units_ago.test.ts, test/en/en_time_units_within.test.ts, test/fr/fr_time_units_ago.test.ts, test/fr/fr_time_units_within.test.ts, test/nl/nl_relative.test.ts, test/nl/nl_time_units_ago.test.ts
Workarounds for https://github.com/wanasit/chrono/issues/439
=> Workaround failed dst tests

src/locales/zh/hans/parsers/ZHHansTimeExpressionParser.ts, src/locales/zh/hant/parsers/ZHHantTimeExpressionParser.ts, test/zh/zh_hans_time_exp.test.ts, test/zh/zh_hant_time_exp.test.ts
Fix: Incorrect date(day) value in Chinese Local time expression parsers when date is not 'Today'.
=> Fix: Incorrect date(day) value in Chinese Local time expression parsers

src/common/refiners/AbstractMergeDateTimeRefiner.ts
Hey, was just reviewing the code and noticed this.
=> Correct name for AbstractMergeDateTimeRefiner

src/locales/ru/parsers/RUTimeUnitCasualRelativeFormatParser.ts, test/ru/ru_time_units_casual_relative.test.ts
Just another option for RUTimeUnitCasualRelativeFormatParser
=> More options for ru "after"

local-test/index.ts, src/index.ts, src/locales/es/constants.ts, src/locales/es/index.ts, src/locales/es/parsers/ESCasualDateParser.ts, src/locales/es/parsers/ESCasualTimeParser.ts, src/locales/es/parsers/ESMonthNameLittleEndianParser.ts, src/locales/es/parsers/ESTimeExpressionParser.ts, src/locales/es/parsers/ESWeekdayParser.ts, src/locales/es/refiners/ESMergeDateRangeRefiner.ts, src/locales/es/refiners/ESMergeDateTimeRefiner.ts, test/es/es_casual.test.ts, test/es/es_month_name_little_endian.test.ts, test/es/es_slash.test.ts, test/es/es_time_exp.test.ts
Cloned and translated from Portuguese implementation due is very similar to Spanish, probably will be making more improvement on the future, based on feed back received by more Spanish-speaking users.
=> Basic spanish support

src/locales/es/index.ts, src/locales/nl/refiners/NLMergeDateRangeRefiner.ts, src/locales/nl/refiners/NLMergeDateTimeRefiner.ts
Just a follow-up for https://github.com/wanasit/chrono/pull/488
=> Fixes descriptions 

src/locales/es/constants.ts, src/locales/es/index.ts, src/locales/es/parsers/ESTimeUnitWithinFormatParser.ts, src/locales/ja/parsers/JPStandardParser.ts, test/es/es_time_units_within.test.ts
Ported the time unit within parser and tests from French to Spanish.
=> [ES] added TimeUnitWithin parser for Spanish

src/locales/de/constants.ts, src/locales/de/index.ts, src/locales/de/parsers/DETimeUnitWithinFormatParser.ts, test/de/de_time_units_within.test.ts
Added Time Unit Within parser and tests for German. I am a native German speaker.
=> [DE] added TimeUnitWithin parser for German

src/locales/ru/parsers/RUCasualDateParser.ts, test/ru/ru_casual.test.ts
More options for ru locale:
1. the day after the day after tomorrow (meaning tomorrow + 2 days)
2. the day before the day before yesterday (meaning yesterday - 2 days)
=> ru: "the day after the day after tomorrow" and "the day before the day before yesterday"

src/results.ts, test/en/en.test.ts
=> Revert "Fix: timezone option for relative dates should affect time"

src/locales/ja/constants.ts, src/locales/ja/index.ts, src/locales/ja/parsers/JPSlashDateFormatParser.ts, src/locales/ja/parsers/JPTimeExpressionParser.ts, src/locales/ja/parsers/JPWeekdayParser.ts, src/locales/ja/parsers/JPWeekdayWithParenthesesParser.ts, src/locales/ja/refiners/JPMergeDateRangeRefiner.ts, src/locales/ja/refiners/JPMergeDateTimeRefiner.ts, src/locales/ja/refiners/JPMergeWeekdayComponentRefiner.ts, test/ja/ja_slash_date_format.test.ts, test/ja/ja_time_exp.test.ts, test/ja/ja_weekday.test.ts
- Add JPSlashDateFormatParser
- Add JPTimeExpressionParser and  JPMergeDateTimeRefiner 
- Add JPWeekdayParser, JPWeekdayWithParenthesesParser and JPMergeWeekdayComponentRefiner
- Add JPMergeDateTimeRefiner 
- Update ja/index to include common configuration
- Add tests related to the above
=> Enhance ja

src/locales/ja/refiners/JPMergeWeekdayComponentRefiner.ts
Close #597 
I'm sorry. My previous PR (#594 ) contained a bug.
I believe this PR will fix it.
=> Fix: Cannnot find module error
