src/parsers/EN/ENTimeExpressionParser.js
test-qunit/test_en_time_exp.js

String.replace only replaces the first occurrence of a string, yielding 'am.'. Change to a regex so we can do a replace all.

Check for 'a.m.'/'p.m.' does not work

---

src/parsers/EN/ENDeadlineFormatParser.js
src/parsers/EN/ENTimeAgoFormatParser.js

Something I did through the web interface, so hopefully it works (I didn't have time to test it, more of a concept).
Should think of `a` and `an` as 1

Support for `a` and `an`

---

src/parsers/EN/ENNowParser

This should fix issue #70. It parses `now` & `today`.
I have not tested this, as I wrote it on the online editor, and I haven't written a test (I don't know exactly how for this project - sorry!)

Now Parser (no tests) - Fixes #70

---

src/parsers/EN/ENCasualDateParser.js

This makes it so `tomorrow` is only pared as `today` one hour after midnight - not the previous 4.
Related to #83

Only imply tomorrow as today 1 hour after midnight

---

src/parsers/EN/ENCasualDateParser.js
src/parsers/ES/ESCasualDateParser.js
test/test_en_casual.js
test/test_es_casual.js

`now` date parser is accurate to milliseconds, so it's a bit more `now` than it currently is.

Make now accurate to milliseconds

---

src/parsers/EN/ENDeadlineFormatParser.js
src/parsers/EN/ENTimeAgoFormatParser.js

This adds the ability to parse for seconds in English “time ago” and “deadline” formats.
It just follows the same pattern as minutes/hours; nothing novel.
Tests all still pass.

Add parsing for seconds

---

src/parsers/EN/ENMonthNameLittleEndianParser.js
src/parsers/EN/ENMonthNameMiddleEndianParser.js
src/parsers/EN/ENMonthNameParser.js
src/parsers/EN/ENTimeExpressionParser.js
src/parsers/ES/ESMonthNameLittleEndianParser.js
src/parsers/ES/ESSlashDateFormatParser.js
src/parsers/FR/FRMonthNameLittleEndianParser.js
src/parsers/FR/FRSlashDateFormatParser.js
test/test_en_little_endian.js
test/test_en_middle_endian.js
test/test_es_little_endian.js
test/test_fr_little_endian.js

In the French and Spanish translations the "BE" (= Buddhist Era) (after the year number) in English was misinterpreted to mean "BC" (= Before Christ). Added and corrected support for "BC" / "AD" in English, French, Spanish.
In French, the abbreviations
- AC
- a. C. n., a. Chr. n.
- p. C. n., p. Chr. n.
are accepted. The fullstops are optional. The abbreviations are not case sensitive.
In Spanish, the abbreviations
- a. C.
- a.d.
- d. C.
are accepted. The fullstops are optional. The abbreviations are not case sensitive.

Added capability to parse AD/BC in year (English, French, Spanish)

---

src/options.js
src/parsers/EN/ENCasualDateParser.js
src/parsers/EN/ENCasualTimeParser.js
src/parsers/parser.js
test/test_en_weekday.js

I found that with the current set up we were able to only do things like "tomorrow morning" or "yesterday afterrnoon" but things like "monday morning" or specific dates with "morning" would not work. 
My suggested solution was to create a casual time parser only for those terms like "morning", "afternoon", etc. We can add more later like "lunch time" "sunset" etc etc
Test passed 100% and I created a test for the day of the week and casual time.
Let me know your thoughts.

Separate "morning" "afternoon" etc logic

---

src/parsers/EN/ENDeadlineFormatParser.js
test/test_en_deadline.js

Currently when a date in Deadline format is parsed it results in a series of known values:
``` 
{  
"ref":"2017-07-25T23:11:17.234Z",
"index":246,
"text":"within 30 days",
"tags":{  
},
"start":{  
"knownValues":{  
"year":2017,
"month":8,
"day":24
},
"impliedValues":{  
"hour":12,
"minute":0,
"second":0,
"millisecond":0
}
}
}
```
Since all the values from this parser are based on the Reference Date, I think it's important to indicate that these are all implied, rather than known.
As far as a use-case goes; I'm currently leveraging this project with historical documents where a reference date can not always be determined. To ensure I don't provide incorrect data, any date which has an implied year/month are removed. Since 'Within 30 days' is being parsed as Today + 30 days, but not …

ENDeadlineFormatParser should have implied rather than known Date values

---

src/parsers/EN/ENSlashDateFormatParser.js
test/test_en_slash.js

It surprised me that the year [chosen] for e.g. `5/31` is reported to be known rather than implied:
```javascript
const ref = new Date(1999, 6-1, 1);
// Expected
chrono.parse('May 31', ref)[0].start.isCertain('year') // => false
chrono.parse('5/31',   ref)[0].start.isCertain('year') // => false
chrono.parse('May 31', ref)[0].start.get('year') // => 1999
chrono.parse('5/31',   ref)[0].start.get('year') // => 1999
chrono.parse('May 31', ref, {forwardDatesOnly: true})[0].start.get('year') // => 2000
chrono.parse('5/31',   ref, {forwardDatesOnly: true})[0].start.get('year') // => 2000
// Actual
chrono.parse('May 31', ref)[0].start.isCertain('year') // => false
chrono.parse('5/31',   ref)[0].start.isCertain('year') // => true
chrono.parse('May 31', ref)[0].start.get('year') // => 1999 …
```

Indicate the implied year when parsing e.g. '5/31'

---

src/parsers/FR/FRSlashDateFormatParser.js
test/test_fr_little_endian.js
test/test_fr_slash.js

"8 Février" and "08/02" are exactly the same in French.
```javascript
chrono.parse("8 Février", new Date(2012,7,10));  // 2013/02/08, the correct date
chrono.parse("08/02", new Date(2012,7,10));  // 2012/02/08
```
```javascript
chrono.parse("08/02", new Date(2012,7,10)) === chrono.parse("8 Février", new Date(2012,7,10));  // 2013/02/08, the correct date
```

Fixing an inconsistency in the dates being parsed

---

package.json

The currently pinned version of moment had several
security issues. This change updates moment to the
most recent version. It also adds nsp to npm test
to check for security vulnerabilities.

Update moment and add nsp security check to tests

---

src/parsers/EN/ENTimeAgoFormatParser.js

For some reason this was only throwing when my project was being bundled with Webpack, not sure if that's relevant or not.  Maybe because "use strict" is added to the bundle?
Regardless it appears to be a bug as index isn't explicitly declared.

Fixed missing var declaration which was throwing.

---

src/parsers/ja/JPStandardParser.js
test/ja/ja_standard.test.js

Japanese emperor Akihito has retired on April 30th, 2019, and 令和 (reiwa) era has stared on May 1st, 2019.
In Japan, the 1st year of Reiwa is called "令和元年"(Reiwa-gannen) and never called "令和1年".
So now (2019-07-27) is called "令和元年7月27日"
https://en.wikipedia.org/wiki/Reiwa
I'd like to make the new era name "令和" and the form of era's 1st year "元年" parseable with chrono.

Implement 令和('reiwa' Japanese era) (2019〜) and 元年(the 1st year of the year)

---

package.json

Loosen the moment dependency so that downstream libraries can choose which version of moment to use.
Currently, consumers are forced to use `moment@2.21.0` if they use `chrono-node`, even if they're already using a more recent version. This causes moment, which uses a stateful singleton for things like the default locale, to load and initialize more than once.

Loosen moment dependency

---

src/parsers/ja/JPStandardParser.js
test/ja/ja_standard.test.js

When parsing '2020年2月29日' at this time (2019-12-17), chrono returns '2020-02-28'.
This is due to the order of registering 'year, month, day' to the `moment` object.
Month & day parts should be registered AFTER year part.
If month & day parts are registered BEFORE year part, 
- chrono tries to make '2019-02-29' `moment` object in the middle of making '2020-02-29'
- `moment` fall back to '2019-02-28' since '2019-02-29' is an invalid date
- then, chrono registers year part and returns '2020-02-28'
I also did some refactorings, that involve this issue.

JpParser: Fixed parsing Feb 29th  leap year while current year is not a leap year.

---

src/parsers/ja/JPStandardParser.js
test/ja/ja_standard.test.js

To enter the new year 2020 (令和2年), we need this.
I think this does not break the accuracy because the parser parse the 1-digit year part like `1年` only if the year part is next to `m月n日`.

JP parser: Capture era year with 1 digit like '令和2年'

---

package.json

`berryboy` -> `wanasit`
Will make the npm page display this repo. Yes, it redirects but it's nicer to just be right in the first place, also allows searching NPM by repo as there are a few similarly named libraries on there.

Update package.json to reflect GitHub repo transfer

---

src/locales/en/parsers/ENTimeUnitWithinFormatParser.ts
src/locales/fr/parsers/FRTimeUnitWithinFormatParser.ts
test/en/en_time_units_within.test.ts
test/fr/fr_time_units_within.test.ts

Support texts like "set a timer for 5 minutes" or "wait for 1 hour".

Fix time unit within using for

---

.travis.yml

[Node 11 and 13 are EOL](https://nodejs.org/en/about/releases/), so this PR updates the tested versions. ~~(I'm also curious if this will also make the test failure I'm seeing in #364 reproducible in CI.)~~ CI for this PR has passed, so the Node version does not appear related to the error in #364.

Update Travis Node versions

---

package.json
test/en/en_relative.test.ts

Bonus: Fix fragile test dealing with time zone offset. Sweden still have summer/winter time.

Bump dayjs & typescript

---

src/locales/en/parsers/ENTimeUnitWithinFormatParser.ts
test/en/en_time_units_within.test.ts

This let's us parse expressions like "give it 2 months" given that
forwardDate is set to true. At the same time if forwardDate is not set,
parsing fails as ambiguous.
Fixes #371

Make "in|within|for" optional if forwardDate=true

---

src/common/parsers/ISOFormatParser.ts
src/locales/nl/constants.ts
src/locales/nl/index.ts
src/locales/nl/parsers/NLCasualDateParser.ts
src/locales/nl/parsers/NLCasualDateTimeParser.ts
src/locales/nl/parsers/NLCasualTimeParser.ts
src/locales/nl/parsers/NLCasualYearMonthDayParser.ts
src/locales/nl/parsers/NLMonthNameMiddleEndianParser.ts
src/locales/nl/parsers/NLMonthNameParser.ts
src/locales/nl/parsers/NLSlashMonthFormatParser.ts
src/locales/nl/parsers/NLTimeExpressionParser.ts
src/locales/nl/parsers/NLTimeUnitWithinFormatParser.ts
src/locales/nl/parsers/NLWeekdayParser.ts
src/locales/nl/refiners/NLMergeDateTimeRefiner.ts
test/nl/nl_casual.test.ts
test/nl/nl_month.test.ts
test/nl/nl_month_name_little_endian.notest.ts
test/nl/nl_month_name_little_endian.test.ts
test/nl/nl_slash.test.ts
test/nl/nl_slash_month.test.ts
test/nl/nl_time_exp.test.ts
test/nl/nl_time_units_within.test.ts
test/nl/nl_weekday.test.ts

I wanted to use this library for the `nl` locale, which was added via PR https://github.com/wanasit/chrono/pull/351. I noticed some parsers where not correct and/or incomplete and missing tests.
Changed/fixed
- Fixed NLMonthNameMiddleEndianParser: "januari 13, 2012" -> "13 januari 2012"
Added:
- Tests for all nl parsers and refiners
- Added NLCasualDateTimeParser for combined words like "morgennamiddag", "vanavond" and "gisterenochtend"
- Added NLCasualYearMonthDayParser for YMD pattern support

Fixed and extend NL locale + add test for all

---

src/index.ts

Previously, the timezones parameter was expecting a a single key with the literal value "string" instead of key-value override pairs

Fix timezones ParsingOption type

---

src/locales/en/parsers/ENRelativeDateFormatParser.ts
src/locales/en/parsers/ENTimeUnitAgoFormatParser.ts
src/locales/en/parsers/ENTimeUnitCasualRelativeFormatParser.ts
src/locales/en/parsers/ENTimeUnitLaterFormatParser.ts
src/locales/en/parsers/ENTimeUnitWithinFormatParser.ts
src/locales/fr/parsers/FRTimeUnitAgoFormatParser.ts
src/locales/fr/parsers/FRTimeUnitRelativeFormatParser.ts
src/locales/fr/parsers/FRTimeUnitWithinFormatParser.ts
src/locales/nl/parsers/NLRelativeDateFormatParser.ts
src/locales/nl/parsers/NLTimeUnitAgoFormatParser.ts
src/locales/nl/parsers/NLTimeUnitCasualRelativeFormatParser.ts
src/locales/nl/parsers/NLTimeUnitLaterFormatParser.ts
src/locales/nl/parsers/NLTimeUnitWithinFormatParser.ts
src/results.ts
src/timezone.ts
test/en/en_relative.test.ts

Previously, any `timezone` value passed in the `reference` parsing context would always result in a non-empty `ReferenceWithTimezone.timezoneOffset`.  In particular, passing `null` would result in a timezone offset of `-0`.
Although there is probably a neater and more maintainable implementation possible, the intent here is to allow the caller to provide a `null` value for `timezone` -- the resulting `timezoneOffset` will only be overridden in cases when `chrono` finds a known/implied timezone in the text.
This is useful in situations where source texts do not have easily-determined timezones, and allows the caller to ignore results that 'look like' times according to `chrono` but where a definite (`isCertain`) timezone is not available.
**NB**: The diff here may be easier to view at this …

Support empty (null) timezone in parser reference date

---

src/common/casualReferences.ts
test/en/en_casual.test.ts

Apologies @wanasit - this bug/gap is something I missed during #411, due to not adding a relevant test case for parsing of text containing the phrase `now`.
The fix is to add the same guard statements around in the `now` function as were [added to the `createRelativeFromReference` function](https://github.com/wanasit/chrono/pull/411/files#diff-1c0edb2e88e4f027868f0b0389e98b0ee10cf56d0949c931f9b5f2c7831bc191L184-R190).
This relates to #407.

Fixup for #411: allow the 'now' casual reference function to support null reference timezones

---

src/common/parsers/AbstractParserWithWordBoundary.ts
src/index.ts
src/locales/zh-hant/constants.ts
src/locales/zh-hant/index.ts
src/locales/zh-hant/parsers/ZHHantCasualDateParser.ts
src/locales/zh-hant/parsers/ZHHantDateParser.ts
src/locales/zh-hant/parsers/ZHHantDeadlineFormatParser.ts
src/locales/zh-hant/parsers/ZHHantRelationWeekdayParser.ts
src/locales/zh-hant/parsers/ZHHantTimeExpressionParser.ts
src/locales/zh-hant/parsers/ZHHantWeekdayParser.ts
src/locales/zh-hant/refiners/ZHHantMergeDateRangeRefiner.ts
src/locales/zh-hant/refiners/ZHHantMergeDateTimeRefiner.ts
test/zh-hant/zh_hant_casual.test.ts
test/zh-hant/zh_hant_date.test.ts
test/zh-hant/zh_hant_deadline.test.ts
test/zh-hant/zh_hant_time_exp.test.ts
test/zh-hant/zh_hant_weekday.test.ts

Migration zh-hant from v1

---

src/timezone.ts

Moscow Time is permanently on UTC+3:00, which was changed from UTC+4:00
in 2014: https://www.worldtimezone.com/dst_news/dst_news_russia65.html
In IANA tzdb:
> Zone Europe/Moscow   2:30:17 -  LMT 1880
>        2:30:17 -  MMT 1916 Jul  3 # Moscow Mean Time
>        2:31:19 Russia %s  1919 Jul  1  0:00u
>        3:00 Russia  %s  1921 Oct
>        3:00 Russia  MSK/MSD 1922 Oct
>        2:00 - EET 1930 Jun 21
>        3:00 Russia  MSK/MSD 1991 Mar 31  2:00s
>        2:00 Russia  EE%sT 1992 Jan 19  2:00s
>        3:00 Russia  MSK/MSD 2011 Mar 27  2:00s
>        4:00 - MSK 2014 Oct 26  2:00s
>        3:00 - MSK

Update MSK to UTC+3:00

---

src/locales/de/parsers/DETimeExpressionParser.ts

The time `4pm` is often represented as `16h` in German.

[DE] Add optional "h" to time expression

---

src/locales/en/constants.ts
test/en/en_relative.test.ts

This supports text like, "next quarter", "last quarter", "next two quarter", "after this quarter".

Added parsing for quarter

---

src/common/refiners/ExtractTimezoneOffsetRefiner.ts
test/en/en_timezone_exp.test.ts

Simple improvement. In making this change, I made a few trade-offs:
* It allows text with an open parenthesis without a closing parenthesis, e.g. `10.30 (UTC+4`. I don't see a huge benefit to disallowing this, and doing so would make the regex much more complex.
* It requires a GMT/UTC prefix to match offsets wrapped in parentheses, i.e. allow `10.30 (UTC+4)`, disallow `10.30 (+4)`. I did this because I have found chrono to be too eager to match math-like expressions. This may, however, be improved in 4756d0dd5b816d3e5aa3b90024e064750ce82f98, so I'm not sure if I have made the right call. On the other hand, I think the `(+4)` format is very rarely used.

Parse timezone offsets that are enclosed in parentheses; restrict max tzOffset

---

README.md

As per https://github.com/wanasit/chrono/blob/c4cd375591f1c51c5e4001814203bda5a838bbdd/src/chrono.ts#L151, it should be "instant" ParsingReference instead of "instance"

fix(README): ParsingReference "instant" instead of "instance"

---

src/locales/fr/parsers/FRTimeUnitWithinFormatParser.ts
src/locales/ja/parsers/JPStandardParser.ts
test/fr/fr_time_units_within.test.ts

Just a small fix for yet another way to specify a duration in French (e.g. régler une minuterie **de** 5 minutes)

[FR] small fix for duration

---

README.md
src/common/casualReferences.ts
src/common/parsers/AbstractParserWithWordBoundary.ts
src/common/parsers/AbstractTimeExpressionParser.ts
src/index.ts
src/locales/ru/constants.ts
src/locales/ru/index.ts
src/locales/ru/parsers/RUCasualDateParser.ts
src/locales/ru/parsers/RUCasualTimeParser.ts
src/locales/ru/parsers/RUMonthNameLittleEndianParser.ts
src/locales/ru/parsers/RUMonthNameParser.ts
src/locales/ru/parsers/RURelativeDateFormatParser.ts
src/locales/ru/parsers/RUTimeExpressionParser.ts
src/locales/ru/parsers/RUTimeUnitAgoFormatParser.ts
src/locales/ru/parsers/RUTimeUnitCasualRelativeFormatParser.ts
src/locales/ru/parsers/RUTimeUnitWithinFormatParser.ts
src/locales/ru/parsers/RUWeekdayParser.ts
src/locales/ru/refiners/RUMergeDateRangeRefiner.ts
src/locales/ru/refiners/RUMergeDateTimeRefiner.ts
test/ru/ru_casual.test.ts
test/ru/ru_month.test.ts
test/ru/ru_month_name_little_endian.test.ts
test/ru/ru_relative.test.ts
test/ru/ru_time_exp.test.ts
test/ru/ru_time_units_ago.test.ts
test/ru/ru_time_units_casual_relative.test.ts
test/ru/ru_time_units_within.test.ts
test/ru/ru_weekday.test.ts

Hey @wanasit as we discussed a few weeks ago, here is the PR with Russian language support.
Also there some changes in "common" codebase. Here is the list and motivation: 
1.  casualReferences.ts - I added a few methods for casual phrases, like "the day after tomorrow" (ru locale has single word definition for it, so I decided to support it) etc. This file looked like a right place for this.
2.  AbstractParserWithWordBoundary.ts - to support Cyrillic analog for \W  I needed to add **u** to RegEx flags and change some common parts of regular expression. Without it it considered Cyrillic letters as non-word characters. I didn't want to affect other locales in any way, at least in this PR since it's big enough on it's own, so I just added a method to this base class with default pattern left …

Adds Russian locale

---

src/locales/ru/constants.ts

Hi, 
I noticed that in ru locale in `parseOrdinalNumberPattern` I used English suffixes. I guess it worked because parseInt just ignores non-digital ending.
Documentation:
> If parseInt encounters a character that is not a numeral in the specified radix, it ignores it and all succeeding characters and returns the integer value parsed up to that point.
I suggest to remove this `replace`.

ru: removes unnecessary replace in parseOrdinalNumberPattern

---

README.md

Adds a little redundancy to README, since the same list is specified on line 40:
> The current fully supported languages are `en`, `ja`, `fr`, `nl` and `ru` (`de`, `pt`, and `zh.hant` are partially supported). 
But maybe it's more clear to have the full list also in **Locale** section.

docs: Corrects supported locale options

---

src/locales/en/parsers/ENCasualTimeParser.ts

Small change to support "midday" as well as "noon"

☀️ Support "midday" casual time in English

---

src/locales/en/parsers/ENTimeExpressionParser.ts
src/locales/en/refiners/ENMergeDateRangeRefiner.ts
test/en/en.test.ts
test/en/en_time_exp.test.ts

Until/till/through were being used as date/time-range joining operators in certain parsers, but not all. I found two parsers in which it made sense to support these operators, and added them in.

Add until/till/through as date/time range expression operators

---

src/locales/nl/constants.ts
test/nl/nl_month.test.ts

March in Dutch is usually shortened as 'mrt', however currently only 'mar' is supported. This adds support for 'mrt'.

Add support for 'mrt' Dutch shortened month

---

package.json
tsconfig.build.esm.json

Output to CommonJS in dist as usual, but add a separate build output in dist/esm that targets ES modules.
My motivation for this change is to optimize performance for the browser. Most importantly this change enables advanced tree-shaking, reducing the size of chrono in bundles by ~80%.
I made an effort to change as little as possible to avoid breaking changes—dependents are now free to choose whether to use the CJS or ESM, and the changes to package.json ensures that most tooling will automatically choose the appropriate version.
There is an argument to be made to switch entirely to ESM, but this would be a breaking change that would make it difficult for CJS packages to use chrono as a dependency. So it is better to target both IMO.

Add ESM build output in addition to CJS

---

src/index.ts

This is a very minor change as it's only a type export. One example where I have needed it is when adding a custom refiner:
```javascript
...
const chronoStrict = chrono.strict.clone();
chronoStrict.refiners.push({refine: (_context, results: Array<ParsingResult>) => results.filter(res => !refineExp.test(res.text))});
```

Expose ParsingResult from index.ts

---

src/locales/ru/constants.ts

- Adds more forms of "minute" in ru locale 
- Changes `let` to `const` where let is redundant

Adds more options for minutes in ru locale

---

src/locales/ja/parsers/JPCasualDateParser.ts
test/ja/ja_casual.test.ts

This PR adds support for Hiragana(ひらがな) in the Japanese date parser.
I didn't know the best way of treating Hiragana/Kanji, so for now I just did it in the most straight forward, or redundant way.
If you have any thoughts on how to improve this, I'd love to challenge myself!
In addition to adding support for Hiragana, I also added some test cases that seemed to be missing.
Btw, thank you so much for writing this library, and I really appreciate how well this library is maintained.

[JA] Add support for Hiragana

---

README.md
src/index.ts
src/locales/uk/constants.ts
src/locales/uk/index.ts
src/locales/uk/parsers/UKCasualDateParser.ts
src/locales/uk/parsers/UKCasualTimeParser.ts
src/locales/uk/parsers/UKMonthNameLittleEndianParser.ts
src/locales/uk/parsers/UKMonthNameParser.ts
src/locales/uk/parsers/UKRelativeDateFormatParser.ts
src/locales/uk/parsers/UKTimeExpressionParser.ts
src/locales/uk/parsers/UKTimeUnitAgoFormatParser.ts
src/locales/uk/parsers/UKTimeUnitCasualRelativeFormatParser.ts
src/locales/uk/parsers/UKTimeUnitWithinFIrmatParser.ts
src/locales/uk/parsers/UKTimeUnitWithinFormatParser.ts
src/locales/uk/parsers/UKWeekdayParser.ts
src/locales/uk/refiners/UKMergeDateRangeRefiner.ts
src/locales/uk/refiners/UKMergeDateTimeRefiner.ts
test/uk/uk_casual.test.ts
test/uk/uk_month.test.ts
test/uk/uk_month_name_little_endian.test.ts
test/uk/uk_relative.test.ts
test/uk/uk_time_exp.test.ts
test/uk/uk_time_units_ago.test.ts
test/uk/uk_time_units_casual_relative.test.ts
test/uk/uk_time_units_within.test.ts
test/uk/uk_weekday.test.ts

- added support for Ukrainian
- added the corresponding tests

Support for Ukrainian (uk)

---

src/locales/fr/refiners/FRMergeDateRangeRefiner.ts
src/locales/fr/refiners/FRMergeDateTimeRefiner.ts
test/fr/fr_casual.test.ts

I add another article _"au"_ for french version, to split start and end dates in the right place.

update regex refine french, add 'au'

---

src/index.ts

We are using the public `ParsedComponents` type, however in https://github.com/wanasit/chrono/commit/feb250d3ca44ff30efb59d62440e576496434d8f when the interfaces where moved `parsing.ts` and later to `types.ts`, `ParsedComponents` was not re-exported again.
There are other interfaces that went private with that change, up to you to decide which ones you want to re-export.

Export `ParsedComponents` again

---

src/calculation/mergingCalculation.ts
src/common/casualReferences.ts
src/locales/en/parsers/ENCasualDateParser.ts
src/locales/en/parsers/ENCasualTimeParser.ts
src/locales/en/parsers/ENTimeExpressionParser.ts
src/results.ts
src/types.ts
test/result.test.ts
test/system.test.ts

A parsing tag or just "tag" is a string attached to parsed components (and results) by parsers and refiners for additional information about the location and context where components were created or modified.
```typescript
const custom = chrono.casual.clone();
custom.parsers.push({
pattern: () => { return /\bChristmas\b/i },
extract: (context, match) => {
return .createParsingComponents({day: 25, month: 12 })
.addTag("USHoliday/chirstmas");
}
});
custom.parsers.push({
pattern: () => { return /\bNew Year\b/i },
extract: (context, match) => {
return .createParsingComponents({day: 1, month: 1 })
.addTag("USHoliday/new_year");
}
});
....
const result = custom.parse("I'll arrive at 2.30AM on Christmas night....")[0];
// To recognize the result from a specific parser... …
```

New: Introduce Parsing Tags

---

src/locales/nl/parsers/NLRelativeDateFormatParser.ts
src/locales/nl/parsers/NLTimeUnitCasualRelativeFormatParser.ts
test/nl/nl_relative.test.ts

Correct in Dutch is "komend uur", not "komende uur".  
And there are some other combinations that were not detected yet: "aankomende maand", "komend jaar" and some more.
In this PR both  
"komend" and "komende",  
"volgend" and "volgende",  
"vorig" and "vorige",
"aankomend" and "aankomende"  
are allowed.
Changed test for "volgende maand" into "aankomende maand", as there are already tests for "volgende week", "volgende dag", "volgend jaar" and no tests for "aankomende".

Improve dutch

---

src/index.ts

Fix `parseDate` returning `Date` instead of `Date | null` in its types.
Setting `"strictNullChecks": true` in `tsconfig.json` will prevent regressions, but that requires some refactoring to satisfy. There are a handful of places that:
- Expect `null` but get a value that could be `undefined`
- Expect `undefined` but get a value that could be `null`
- Expect a non-nullish type but get a value that could be nullish

Fix parseDate return type not nullable

---

src/locales/ja/parsers/JPCasualDateParser.ts
src/locales/ja/refiners/JPMergeDateRangeRefiner.ts
test/ja/ja_casual.test.ts
test/ja/ja_standard.test.ts

- I removed "当日" on `JPCasualDateParser`. Because "当日" means that day or the day, not today.  
- I added "本日" as today on `JPCasualDateParser`
- I added "~" and "～" as patternBetween on `JPMergeDateRangeRefiner`. They are often used in Japanese.

Improve Japanese

---

src/locales/it/constants.ts
src/locales/it/index.ts
src/locales/it/parsers/ITCasualDateParser.ts
src/locales/it/parsers/ITCasualTimeParser.ts
src/locales/it/parsers/ITCasualYearMonthDayParser.ts
src/locales/it/parsers/ITMonthNameLittleEndianParser.ts
src/locales/it/parsers/ITMonthNameMiddleEndianParser.ts
src/locales/it/parsers/ITMonthNameParser.ts
src/locales/it/parsers/ITRelativeDateFormatParser.ts
src/locales/it/parsers/ITSlashMonthFormatParser.ts
src/locales/it/parsers/ITTimeExpressionParser.ts
src/locales/it/parsers/ITTimeUnitAgoFormatParser.ts
src/locales/it/parsers/ITTimeUnitCasualRelativeFormatParser.ts
src/locales/it/parsers/ITTimeUnitLaterFormatParser.ts
src/locales/it/parsers/ITTimeUnitWithinFormatParser.ts
src/locales/it/parsers/ITWeekdayParser.ts
src/locales/it/refiners/ITMergeDateRangeRefiner.ts
src/locales/it/refiners/ITMergeDateTimeRefiner.ts
src/locales/it/refiners/ITMergeRelativeDateRefiner.ts

Added locales/it translations for Italian Language support

Added Italian Locale

---

src/common/casualReferences.ts

Making "noon" consistent with "midnight".
This is important to me because (for some unknown reason) 12 is by default implied for hour.  So I have code to check to see if hour is "implied" vs "known", and I throw it out if it's implied and set it to zero.  But for this "noon" I was throwing it out, which is not desired.
An alternative solution for me would be to allow a default hour to be set in config rather than implying 12.
Should the minute/second/milliseconds also be known for both midnight and noon?  Doesn't a

Fix noon to make hour a known value rather than an implied value

---

src/locales/sv/constants.ts
src/locales/sv/index.ts
src/locales/sv/parsers/SVCasualDateParser.ts
src/locales/sv/parsers/SVMonthNameLittleEndianParser.ts
src/locales/sv/parsers/SVWeekdayParser.ts
test/sv/sv_casual.test.ts
test/sv/sv_weekday.test.ts

- Add Swedish language constants and parsers
- Support for casual expressions (idag, imorgon, igår)
- Support for weekday expressions (måndag, nästa fredag)
- Support for month/date formats (15 januari, 23 december 2024)
- Add comprehensive test suite with 5 passing tests
- Compatible with existing Chrono architecture

Add Swedish localization for Chrono

---

src/common/parsers/AbstractTimeExpressionParser.ts
test/en/en_time_exp.test.ts

The `AbstractTimeExpressionParser` was incorrectly parsing 4-digit numbers as times (e.g., '2019' as 20:19). This caused issues with year ranges like '2019 to 2020' being parsed as a time.
This change adds a check to the parser to prevent this. A 4-digit number is no longer considered a time if it is not accompanied by a minute part or an AM/PM specifier.
A test case has been added to ensure that '2019 to 2020' is not parsed as a time.

Fix: Do not parse year-like numbers as times

---

test/sv/sv_casual.test.ts
test/sv/sv_month_name_little_endian.test.ts
test/zh/hans/zh_hans_time_exp.test.ts

I have increased test coverage for the Swedish (sv) locale by:
1.  Adding a new test file `test/sv/sv_month_name_little_endian.test.ts` to cover parsing of dates with month names (e.g., "15 augusti 2012"). This file tests single dates, date ranges, and impossible dates.
2.  Adding numerous new test cases to `test/sv/sv_casual.test.ts` for previously untested casual date and time expressions, such as "nu", "övermorgon", "i förrgår", and combined expressions like "imorgon kväll".
While adding these tests, I identified a pre-existing bug in the `SVCasualDateParser`, which causes combined expressions like "imorgon kväll" to be parsed incorrectly. As you instructed, fixing this bug is out of scope for this change. Therefore, I have commented out the new tests that fail due to this bug with …

feat(test): Increase test coverage for Swedish locale

---

src/locales/de/parsers/DETimeUnitRelativeFormatParser.ts
src/locales/en/refiners/ENMergeRelativeAfterDateRefiner.ts
src/locales/fr/parsers/FRTimeUnitAgoFormatParser.ts
src/locales/fr/parsers/FRTimeUnitRelativeFormatParser.ts
src/locales/it/parsers/ITTimeUnitAgoFormatParser.ts
src/locales/it/parsers/ITTimeUnitCasualRelativeFormatParser.ts
src/locales/it/refiners/ITMergeRelativeDateRefiner.ts
src/locales/nl/parsers/NLTimeUnitAgoFormatParser.ts
src/locales/nl/parsers/NLTimeUnitCasualRelativeFormatParser.ts
src/locales/ru/parsers/RUTimeUnitAgoFormatParser.ts
src/locales/ru/parsers/RUTimeUnitCasualRelativeFormatParser.ts
src/locales/uk/parsers/UKTimeUnitAgoFormatParser.ts
src/locales/uk/parsers/UKTimeUnitCasualRelativeFormatParser.ts
src/utils/timeunits.ts

Replaced all usages of the deprecated `timeunits.reverseTimeUnits` function with `duration.reverseDuration` from the calculation utilities.
This change affects parsers and refiners across multiple locales that handle relative time expressions. The deprecated function has been removed from the codebase.

Refactor: Remove deprecated timeunits.reverseTimeUnits

---

test/zh/hans/zh_hans_casual.test.ts
test/zh/hans/zh_hans_date.test.ts
test/zh/hans/zh_hans_weekday.test.ts
test/zh/hant/zh_hant_casual.test.ts
test/zh/hant/zh_hant_date.test.ts
test/zh/hant/zh_hant_weekday.test.ts

This adds more unit tests for `zh/hans` and `zh/hant` to increase test coverage.

feat(test): Add more unit tests for zh locales

---

test/sv/sv_casual.test.ts

Add more test cases to `test/sv/sv_casual.test.ts` to increase test coverage for `src/locales/sv/parsers/SVCasualDateParser.ts`.
The new tests cover:
- Additional date keywords: "nu", "i förrgår".
- All time-of-day keywords in combination with "idag på...".
Some cases were not tested due to pre-existing bugs in the parser:
- "imorn" is not in the parser's regex.
- `övermorgon` is in the regex but not implemented in the parser logic.
- Combinations of date and time without "på" (e.g., "idag morgon") are not parsed correctly.
- Combinations of time with "imorgon" or "igår" are not parsed correctly due to an issue with time implication.

test(sv): Increase test coverage for SVCasualDateParser
